---
output: 
  bookdown::pdf_document2:
    includes:
      in_header: preamble.tex
    pandoc_args: 
      - "--metadata-file=../Header/header_common.yaml"
      - '--lua-filter=../Filters/scholarly-metadata.lua'
      - '--lua-filter=../Filters/author-info-blocks.lua'
    toc: no
params:
  X: NULL
graphics: yes
csl: plos.csl
bibliography: ../Data/bib.bib
subtitle: Suplementary Material
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage[normalem]{ulem}
- \usepackage{threeparttablex}
- \usepackage{makecell}
---

```{r echo = F, warning=FALSE}
library(xtable)
#options(xtable.floating = FALSE)
options(xtable.timestamp = "")
```
```{r echo = F}
X <- params$X
params_ls<- list(figures_in_body_lgl = X@figures_in_body_lgl,
                 output_type_1L_chr = X@outp_formats_chr[1],
                 results_ls = X@b_SpecificResults@a_SpecificShareable@shareable_outp_ls$results_ls,
                 tables_in_body_lgl = X@tables_in_body_lgl)
results_ls <- params_ls$results_ls

```

```{r child="../Child_RMDs/TA_Content.Rmd", echo=FALSE, warning=FALSE}
```
