---
title: "TTU"
author: "Matthew Hamilton"
date: "26/01/2021"
output: html_document
---

## TTU regression model performance 
<!-- Table start -->The 10-fold cross-validated model fitting index from TTU models using `r results_ls$ttu_cs_ls$cs_mdls_predrs_seq_dscdng_chr[1]` are reported in `r ifelse(params$output_type_1L_chr=="Word","","Table")` \@ref(tab:tenfoldolstb) in the Supplementary Material<!-- Table end -->. <!-- Author judgment start --> The best `r names(results_ls$ttu_cs_ls$best_mdl_types_ls)[2]` model was found to be either `r results_ls$ttu_cs_ls$best_mdl_types_ls[[2]] %>% paste0(collapse = ", ") %>% stringi::stri_replace_last(fixed = ",", " or")`<!-- Comment end -->.  <!-- Comment start: Depends on length of selected model vectors -->Both<!-- Comment end --> `r results_ls$ttu_cs_ls$selected_mdls_chr %>% paste0(collapse = ", ") %>% stringi::stri_replace_last(fixed = ",", " and")` were selected for further evaluation. Predictive ability of each candidate predictor using baseline data were also compared using 10-fold cross-validation.  

<!-- Table start -->As shown in `r ifelse(params$output_type_1L_chr=="Word","","Table")` \@ref(tab:tenfoldglmtb),<!-- Table end --> `r results_ls$ttu_cs_ls$cs_mdls_predrs_seq_dscdng_chr[1]` had the highest predictive ability <!-- Comment start: Requires at least 3 predictors to be compared -->followed by `r results_ls$ttu_cs_ls$cs_mdls_predrs_seq_dscdng_chr[2:(length(results_ls$ttu_cs_ls$cs_mdls_predrs_seq_dscdng_chr)-1)] %>% paste0(collapse = ", ") %>% stringi::stri_replace_last(fixed = ",", " and")`. `r results_ls$ttu_cs_ls$cs_mdls_predrs_seq_dscdng_chr[length(results_ls$ttu_cs_ls$cs_mdls_predrs_seq_dscdng_chr)]` had the least predictive capability.<!-- Comment end --> <!-- Author judgment start -->This `r results_ls$ttu_cs_ls$mdl_predrs_and_rf_seqs_cmprsn_1L_chr` with <!-- Author judgment end -->the random forest model in which `r results_ls$ttu_cs_ls$rf_seq_dscdng_chr[1]` was found to be the most ‘important’ predictor <!-- Figure start -->(see Figure \@ref(fig:importance))<!-- Figure end-->.  The confounding effect of other participant characteristics were also evaluated when using the candidate predictors in predicting utility score<!-- Comment start: Consider adding these results --><!-- Comment end -->.  Using the baseline data, `r ifelse(is.na(results_ls$ttu_cs_ls$sig_covars_all_predrs_mdls_chr[1]),"no confounding factor",results_ls$ttu_cs_ls$sig_covars_all_predrs_mdls_chr %>% paste0(collapse = ", ") %>% stringi::stri_replace_last(fixed = ",", " and"))` `r ifelse(is.na(results_ls$ttu_cs_ls$sig_covars_all_predrs_mdls_chr[1]),"was",ifelse(length(results_ls$ttu_cs_ls$sig_covars_all_predrs_mdls_chr)==1,"was","were"))` found to independently predict utility scores in models for all six candidate predictors *(p<`r results_ls$ttu_cs_ls$sig_thresh_covars_1L_chr`)*.  `r results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[1,]$covars_ls[[1]] %>% paste0(collapse = ", ") %>% stringi::stri_replace_last(fixed = ",", " and")` `r ifelse(length(results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[1,]$covars_ls[[1]])==1,"was","were")` identified for the `r results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[1,]$predrs_mdls_ls[[1]] %>% paste0(collapse = ", ") %>% stringi::stri_replace_last(fixed = ",", " and")` prediction model`r ifelse(length(results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[1,]$predrs_mdls_ls[[1]])==1,"","s")`; `r results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[2,]$covars_ls[[1]] %>% paste0(collapse = ", ") %>% stringi::stri_replace_last(fixed = ",", " and")` `r ifelse(length(results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[2,]$predrs_mdls_ls[[1]])==1,"was","were")` found to be `r ifelse(length(results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[2,]$predrs_mdls_ls[[1]])==1,"a","")` confounder`r ifelse(length(results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[2,]$predrs_mdls_ls[[1]])==1,"","s")` for `r results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[2,]$predrs_mdls_ls[[1]] %>% paste0(collapse = ", ") %>% stringi::stri_replace_last(fixed = ",", " and")` model`r ifelse(length(results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[2,]$predrs_mdls_ls[[1]])==1,"","s")` *(p<`r results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[2,]$sig_thresh_dbl`)*. A few other confounders, including `r results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[3,]$covars_ls[[1]] %>% paste0(collapse = ", ") %>% stringi::stri_replace_last(fixed = ",", " and")` were identified as `r results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[3,]$assn_strgth_chr` associated with utility in TTU models using `r results_ls$ttu_cs_ls$sig_covars_some_predrs_mdls_tb[3,]$predrs_mdls_ls[[1]]`.  

